#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

usuarios:
  path: /usuarios
  methods: GET
  controller: App\Controller\UsuariosController::getUsuarios

cadastrarUsuarios:
  path: /usuarios
  methods: POST
  controller: App\Controller\UsuariosController::insertUsuarios

atualizarUsuarios:
  path: /usuarios
  methods: PUT
  controller: App\Controller\UsuariosController::updateUsuarios